export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FALIURE = 'GET_USER_FALIURE'
export const GET_USER_REQUEST = 'GET_USER_REQUEST'


export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FALIURE = 'USER_LOGIN_FALIURE'

export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'